# train_model.py
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
import joblib

# 1) Sample training data (you should expand this with more examples)
texts = [
    # Phishing-like
    "Urgent: Verify your account now click this link to avoid suspension",
    "Unusual activity on your bank account please login immediately",
    "Password reset required click here to keep your account safe",
    "Your account has been locked verify your identity",

    # Legit emails
    "Meeting scheduled for tomorrow with project team",
    "Invoice for your recent purchase attached",
    "Your subscription has been renewed successfully",
    "Lunch plans for today?",
    "Reminder: assignment submission deadline extended",

    # AI-generated style
    "This email was generated by AI to assist with your inquiry",
    "As an AI language model I recommend the following steps",
    "This response is automatically generated by our AI assistant",
    "Using advanced AI algorithms we created this summary"
]

labels = [
    "phishing", "phishing", "phishing", "phishing",
    "legit", "legit", "legit", "legit", "legit",
    "ai_generated", "ai_generated", "ai_generated", "ai_generated"
]

# 2) Build pipeline: TF-IDF + Logistic Regression
pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1)),
    ("clf", LogisticRegression(max_iter=1000))
])

# 3) Train-test split (optional, just to see accuracy)
X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.2, random_state=42, stratify=labels
)

pipeline.fit(X_train, y_train)

print("Train score:", pipeline.score(X_train, y_train))
print("Test score:", pipeline.score(X_test, y_test))

# 4) Save model
joblib.dump(pipeline, "email_classifier.joblib")
print("Model saved to email_classifier.joblib")
